=== fairtracks/fairtracks_standard/json/schema/fairtracks_study.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/fairtracks/fairtracks_standard/v1/current/json/schema/fairtracks_study.schema.json",
    "$comment": "JSON signature: a99cfc3734243f8e0700c57a082afff1e1ac86d3a9946a6a420a523d524a847e",
    "title": "Study",
    "type": "object",
    "properties": {
        "@schema": {
            "description": "The JSON Schema absolute URL. Used to link JSON data to a JSON schema. Must match the value of '$id' in the linked schema",
            "type": "string",
            "format": "uri",
            "pattern": "^(https?|ftp)://",
            "const": "https://raw.githubusercontent.com/fairtracks/fairtracks_standard/v1/current/json/schema/fairtracks_study.schema.json"
        },
        "global_id": {
            "description": "Global study identifier, resolvable by identifiers.org",
            "type": "string",
            "format": "curie",
            "namespace": [
                "geo",
                "ega.study"
            ],
            "matchType": "canonical",
            "examples": [
                "geo:GSE35583"
            ]
        },
        "local_id": {
            "description": "Submitter-local identifier (within the track collection) for the study",
            "type": "string",
            "examples": [
                "UW_ChipSeq"
            ],
            "unique": true
        },
        "collection_ref": {
            "description": "Reference to the track collection containing the study (using the submitter-local identifier of the collection)",
            "type": "string",
            "format": "foreign_ref",
            "examples": [
                "encode_example"
            ],
            "foreignProperty": "https://raw.githubusercontent.com/fairtracks/fairtracks_standard/v1/1.0.1/json/schema/fairtracks.schema.json#collection_info/local_id",
            "autogenerated": true
        },
        "study_name": {
            "description": "Name of the study",
            "type": "string",
            "examples": [
                "Histone Modifications by ChIP-seq from ENCODE/University of Washington"
            ]
        },
        "publication": {
            "description": "Pubmed identifier (dataset or publication)",
            "type": "string",
            "format": "curie",
            "namespace": "pubmed",
            "matchType": "canonical",
            "examples": [
                "pubmed:22955617"
            ]
        },
        "contact": {
            "description": "Contact information for study",
            "type": "object",
            "$ref": "https://raw.githubusercontent.com/fairtracks/fairtracks_standard/v1/1.0.1/json/schema/fairtracks_contact.schema.json"
        }
    },
    "required": [
        "local_id",
        "study_name",
        "contact"
    ],
    "additionalProperties": true
}

=== fairtracks/fairtracks_standard/json/examples/fairtracks_study.example.json
{
    "@schema": "https://raw.githubusercontent.com/fairtracks/fairtracks_standard/v1/current/json/schema/fairtracks_study.schema.json",
    "global_id": "geo:GSE35583",
    "local_id": "UW_ChipSeq",
    "collection_ref": "encode_example",
    "study_name": "Histone Modifications by ChIP-seq from ENCODE/University of Washington",
    "publication": "pubmed:22955617",
    "contact": {
        "name": "ENCODE DCC",
        "e-mail": "encode-help@lists.stanford.edu"
    }
}
